export const ARTICLES_LIST = {
  data: [
    {
      id: 4,
      documentId: "xsinv9zacb4fddn3vo48pmie",
      title: "Sample Test 2",
      description: "Sample Description 2",
      cover_image_url:
        "https://res.cloudinary.com/yeremia-alfa-dio/image/upload/v1727703810/large_Welcome_Scan_84f3de8212.jpg",
      createdAt: "2024-10-02T01:22:56.307Z",
      updatedAt: "2024-10-02T01:22:56.307Z",
      publishedAt: "2024-10-02T01:22:57.493Z",
      locale: null,
      user: {
        id: 2,
        documentId: "c5bukvbbkszs7he29fgvdyke",
        username: "yeremiadio",
        email: "raikkonendio@gmail.com",
        provider: "local",
        confirmed: true,
        blocked: false,
        createdAt: "2024-10-01T13:18:12.513Z",
        updatedAt: "2024-10-01T13:18:12.513Z",
        publishedAt: "2024-10-01T13:18:12.513Z",
        locale: null,
      },
      category: null,
      comments: [
        {
          id: 2,
          documentId: "bvexgqn5sim938kl13f3cfho",
          content: "This is my logged comment from user test",
          createdAt: "2024-10-11T11:22:47.079Z",
          updatedAt: "2024-10-11T11:22:47.079Z",
          publishedAt: "2024-10-11T11:22:48.368Z",
          locale: null,
        },
        {
          id: 4,
          documentId: "h49fg7xk0l1ddrshevur6110",
          content: "Second Comment",
          createdAt: "2024-10-11T11:27:33.271Z",
          updatedAt: "2024-10-11T11:27:33.271Z",
          publishedAt: "2024-10-11T11:27:34.515Z",
          locale: null,
        },
      ],
      localizations: [],
    },
    {
      id: 6,
      documentId: "q1xccl0gwemgt7t9471z35hp",
      title: "Sample Test",
      description: "Sample Description",
      cover_image_url:
        "https://res.cloudinary.com/yeremia-alfa-dio/image/upload/v1727829875/large_7b48cd200b65f59715ef01883fb7999b_41e596882a.jpg",
      createdAt: "2024-10-02T00:43:23.947Z",
      updatedAt: "2024-10-02T01:33:57.477Z",
      publishedAt: "2024-10-02T01:33:59.105Z",
      locale: null,
      user: {
        id: 2,
        documentId: "c5bukvbbkszs7he29fgvdyke",
        username: "yeremiadio",
        email: "raikkonendio@gmail.com",
        provider: "local",
        confirmed: true,
        blocked: false,
        createdAt: "2024-10-01T13:18:12.513Z",
        updatedAt: "2024-10-01T13:18:12.513Z",
        publishedAt: "2024-10-01T13:18:12.513Z",
        locale: null,
      },
      category: null,
      comments: [],
      localizations: [],
    },
    {
      id: 9,
      documentId: "qzkocrykudblfmtdxq4dsr97",
      title: "Sample Test 1",
      description: "Sample Description 1",
      cover_image_url:
        "https://res.cloudinary.com/yeremia-alfa-dio/image/upload/v1727703810/large_Welcome_Scan_84f3de8212.jpg",
      createdAt: "2024-10-02T03:01:51.446Z",
      updatedAt: "2024-10-02T03:19:24.450Z",
      publishedAt: "2024-10-02T03:19:28.328Z",
      locale: null,
      user: {
        id: 1,
        documentId: "ovrbscwihfyfpu51tvbwe6ju",
        username: "test",
        email: "test@gmail.com",
        provider: "local",
        confirmed: true,
        blocked: false,
        createdAt: "2024-10-01T12:36:32.694Z",
        updatedAt: "2024-10-01T12:36:32.694Z",
        publishedAt: "2024-10-01T12:36:32.789Z",
        locale: null,
      },
      category: null,
      comments: [],
      localizations: [],
    },
    {
      id: 12,
      documentId: "msxjhhsow01iy9jydhi1v0ru",
      title: "Chat GPT is Good",
      description: "Sample Description 1",
      cover_image_url:
        "https://res.cloudinary.com/yeremia-alfa-dio/image/upload/v1727703810/large_Welcome_Scan_84f3de8212.jpg",
      createdAt: "2024-10-11T19:06:07.582Z",
      updatedAt: "2024-10-11T19:06:07.582Z",
      publishedAt: "2024-10-11T19:06:08.906Z",
      locale: null,
      user: {
        id: 1,
        documentId: "ovrbscwihfyfpu51tvbwe6ju",
        username: "test",
        email: "test@gmail.com",
        provider: "local",
        confirmed: true,
        blocked: false,
        createdAt: "2024-10-01T12:36:32.694Z",
        updatedAt: "2024-10-01T12:36:32.694Z",
        publishedAt: "2024-10-01T12:36:32.789Z",
        locale: null,
      },
      category: null,
      comments: [],
      localizations: [],
    },
    {
      id: 14,
      documentId: "rvbqpbpbgxjbqgofxdwiq09p",
      title: "Trenggalek Berteman HAti",
      description:
        "Pada zaman dahulu Trenggalek terkenal daerah yang tandus dan kering, sehingga banyak orang makan nasi tiwul / gaplek. Hal itu menjadikan rasa keprihatinan bagi punggawa pemerintahan Kadipaten Trenggalek khususnya Adipati Minak Sopal. Karena rasa tanggung jawabnya terhadap rakyatnya, maka Adipati Minak Sopal punya gagasan untuk membangun Dam agar airnya bias mengaliri sawah-sawah yang ada di wilayah Trenggalek yang dulu terkenal sawah tadah hujan. Dalam mewujudkan gagasan itu Adipati Minak Sopal membangun Dam di daerah Bagong.Untuk membangun Dam Bagong tidak mudah karena arus air dari kawasan utara sangat besar sehingga Dam itu jebol dan rusak. Jebol dan rusaknya Dam itu ternyata karena ulah dari Penguasa Kawasan Gunung Wilis yang terkenal sakti bernama Raja Bedander. Konon Raja Bedander bermusuhan dengan Adipati Minak Sopal karena perebutan wilayah. Untuk itu Raja Bedander mengancam Trenggalek akan dimusnahkan dengan cara mendatangkan air yang besar dari sungai sebelah utara Trenggalek. Karena ada ancaman dari Raja Bedander maka Adipati Minakm Sopal berupaya menanggulangi dengan cara membuat Dam Bagong.Namun sebelum mengulas tentang Dam Bagong perlu kita menyimak peristiwa permusuhan Raja Bedander dengan Adipati Minak Sopal. Dulu Raja Bedander mempunyai wilayah di kawasan lereng Gunung Wilis. Karena ambisinya dia ingin mengembangkan wilayah ke selatan.Wilayah selatan adalah wilayah kawasan Adipati Minak Sopal sehingga terjadi perebutan wilayah. Agar tidak mengorbankan rakyatnya maka Adipati Minak Sopal mengajak bertanding Raja Bedander adu kesaktian. Karena tantangan dari Adipati Minak Sopal maka Raja Bedander beserta prajuritnya berangkat bersama-sama menuju Trenggalek, Karena perjalanannya dari lereng Gunung Wilis sangat jauh, maka rombongan Raja Bedander beristirahat di daerah Srabah dengan menancapkan payungnya di tanah yang akhirnya sampai sekarang bekas istirahatnya Raja Bedander di Srabah dinamai Watu Payung karena ada batu yang menyerupai payung.Usai istirahat di Srabah berangkat ke selatan. Di selatan desa Srabah rombongan Raja Bedander istirahat lagi sambil menghibur diri dengan diiringi gamelan. Rasa capeknya sudah hilang rombongan berangkat lagi ke selatan.",
      cover_image_url:
        "https://is3.cloudhost.id/img-kbrt/2022/09/Fakta-Fakta-menarik-tentang-Trenggalek-yang-jarang-diketahui.jpg",
      createdAt: "2024-10-11T19:45:42.784Z",
      updatedAt: "2024-10-11T19:45:42.784Z",
      publishedAt: "2024-10-11T19:45:44.223Z",
      locale: null,
      user: {
        id: 1,
        documentId: "ovrbscwihfyfpu51tvbwe6ju",
        username: "test",
        email: "test@gmail.com",
        provider: "local",
        confirmed: true,
        blocked: false,
        createdAt: "2024-10-01T12:36:32.694Z",
        updatedAt: "2024-10-01T12:36:32.694Z",
        publishedAt: "2024-10-01T12:36:32.789Z",
        locale: null,
      },
      category: {
        id: 3,
        documentId: "ry6927r086nkrpmprmx8is5u",
        name: "Village",
        description: null,
        createdAt: "2024-10-11T08:47:32.977Z",
        updatedAt: "2024-10-11T08:47:32.977Z",
        publishedAt: "2024-10-11T08:47:32.972Z",
        locale: null,
      },
      comments: [],
      localizations: [],
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 25,
      pageCount: 1,
      total: 5,
    },
  },
};

export const ARTICLE_DETAIL = {
  id: 14,
  documentId: "rvbqpbpbgxjbqgofxdwiq09p",
  title: "Trenggalek Berteman HAti",
  description:
    "Pada zaman dahulu Trenggalek terkenal daerah yang tandus dan kering, sehingga banyak orang makan nasi tiwul / gaplek. Hal itu menjadikan rasa keprihatinan bagi punggawa pemerintahan Kadipaten Trenggalek khususnya Adipati Minak Sopal. Karena rasa tanggung jawabnya terhadap rakyatnya, maka Adipati Minak Sopal punya gagasan untuk membangun Dam agar airnya bias mengaliri sawah-sawah yang ada di wilayah Trenggalek yang dulu terkenal sawah tadah hujan. Dalam mewujudkan gagasan itu Adipati Minak Sopal membangun Dam di daerah Bagong.Untuk membangun Dam Bagong tidak mudah karena arus air dari kawasan utara sangat besar sehingga Dam itu jebol dan rusak. Jebol dan rusaknya Dam itu ternyata karena ulah dari Penguasa Kawasan Gunung Wilis yang terkenal sakti bernama Raja Bedander. Konon Raja Bedander bermusuhan dengan Adipati Minak Sopal karena perebutan wilayah. Untuk itu Raja Bedander mengancam Trenggalek akan dimusnahkan dengan cara mendatangkan air yang besar dari sungai sebelah utara Trenggalek. Karena ada ancaman dari Raja Bedander maka Adipati Minakm Sopal berupaya menanggulangi dengan cara membuat Dam Bagong.Namun sebelum mengulas tentang Dam Bagong perlu kita menyimak peristiwa permusuhan Raja Bedander dengan Adipati Minak Sopal. Dulu Raja Bedander mempunyai wilayah di kawasan lereng Gunung Wilis. Karena ambisinya dia ingin mengembangkan wilayah ke selatan.Wilayah selatan adalah wilayah kawasan Adipati Minak Sopal sehingga terjadi perebutan wilayah. Agar tidak mengorbankan rakyatnya maka Adipati Minak Sopal mengajak bertanding Raja Bedander adu kesaktian. Karena tantangan dari Adipati Minak Sopal maka Raja Bedander beserta prajuritnya berangkat bersama-sama menuju Trenggalek, Karena perjalanannya dari lereng Gunung Wilis sangat jauh, maka rombongan Raja Bedander beristirahat di daerah Srabah dengan menancapkan payungnya di tanah yang akhirnya sampai sekarang bekas istirahatnya Raja Bedander di Srabah dinamai Watu Payung karena ada batu yang menyerupai payung.Usai istirahat di Srabah berangkat ke selatan. Di selatan desa Srabah rombongan Raja Bedander istirahat lagi sambil menghibur diri dengan diiringi gamelan. Rasa capeknya sudah hilang rombongan berangkat lagi ke selatan.",
  cover_image_url:
    "https://is3.cloudhost.id/img-kbrt/2022/09/Fakta-Fakta-menarik-tentang-Trenggalek-yang-jarang-diketahui.jpg",
  createdAt: "2024-10-11T19:45:42.784Z",
  updatedAt: "2024-10-11T19:45:42.784Z",
  publishedAt: "2024-10-11T19:45:44.223Z",
  locale: null,
  user: {
    id: 1,
    documentId: "ovrbscwihfyfpu51tvbwe6ju",
    username: "test",
    email: "test@gmail.com",
    provider: "local",
    confirmed: true,
    blocked: false,
    createdAt: "2024-10-01T12:36:32.694Z",
    updatedAt: "2024-10-01T12:36:32.694Z",
    publishedAt: "2024-10-01T12:36:32.789Z",
    locale: null,
  },
  category: {
    id: 3,
    documentId: "ry6927r086nkrpmprmx8is5u",
    name: "Village",
    description: null,
    createdAt: "2024-10-11T08:47:32.977Z",
    updatedAt: "2024-10-11T08:47:32.977Z",
    publishedAt: "2024-10-11T08:47:32.972Z",
    locale: null,
  },
  comments: [
    {
      id: 2,
      documentId: "bvexgqn5sim938kl13f3cfho",
      content: "This is my logged comment from user test",
      createdAt: "2024-10-11T11:22:47.079Z",
      updatedAt: "2024-10-11T11:22:47.079Z",
      publishedAt: "2024-10-11T11:22:48.368Z",
      locale: null,
    },
    {
      id: 4,
      documentId: "h49fg7xk0l1ddrshevur6110",
      content: "Second Comment",
      createdAt: "2024-10-11T11:27:33.271Z",
      updatedAt: "2024-10-11T11:27:33.271Z",
      publishedAt: "2024-10-11T11:27:34.515Z",
      locale: null,
    },
  ],
  localizations: [],
};
